### ISSUE TITLE
TUMAT 1.10.2 "unknown" blocks

### ISSUE THREAD

**Issue by iBELLinc** [canitzp/TUMAT#8] opened 2017-07-12 23:21 UTC
This is most likely not an issue with TUMAT itself. I am looking for some guidance to figure out what is causing this problem so I can fix it.

In the newest (or final?) version (1.6.0) of TUMAT for 1.10.2 I am getting a weird issue where all blocks are labeled as **"unknown" Minecraft** by TUMAT when looking down at them regardless of whether it is added by a mod or not. Everything is properly displayed in all other directions except when looking down past a certain angle.

This is especially annoying when working with crops because it won't show any information about them. It simply says "unknown" and you can't tell what % growth it is at or what crop it is for that matter.

I have another modpack that uses the same version of TUMAT and does not have this issue. Both packs are 1.10.2 but the correctly working one has around 40 mods and the modpack with this issue has over 100.

Is there something in particular that would cause this to happen? Or does this sound like a compatibility problem with another mod? I did not see a list of incompatible mods anywhere.

**Comment by canitzp** [comment] 2017-07-13 06:48
That is a incompatibility with a mod, but I never heared of this issue, so your only way to figure out what causes the issue is to remove one mod then try to reproduce the issue and remove the next if it still happens

**Comment by iBELLinc** [comment] 2017-07-13 06:58
Thanks for the quick response! I'll look into it and let you know what I find.

**Comment by iBELLinc** [comment] 2017-09-30 05:18
Sorry it took so long to get back to you. I have found the culprit to be iChunUtil library for 1.10.2.
So far I have tested 6.4.0 and 6.5.0 and both cause this issue.

The mod can be found here: https://minecraft.curseforge.com/projects/ichunutil/files

**Comment by canitzp** [comment] 2017-10-28 14:45
Fixed in the MC 1.12.x version.

**Closed as completed by canitzp** 2017-10-28 14:45 UTC
